# Generated by Django 5.0.2 on 2024-03-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkmodel',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.categorymodel'),
        ),
    ]
